### ISSUE TITLE
Pasting from clipboard makes two duplicates rather than one

### ISSUE THREAD

**Issue by pihart** [cjquines/qboard#24] opened 2020-10-09 21:42 UTC
After fixing #23

**Comment by pihart** [comment] 2020-10-09 22:08
Issue happens when object is in both qboard and device clipboard

**Comment by pihart** [comment] 2020-10-09 22:13
Additionally, both qboard and device clipboard are pasted from. Reproduce: copy an external image and paste into qboard. Now copy the pasted one and paste it again. You have 3 images on the screen

**Comment by cjquines** [comment] 2020-10-09 23:38
cannot reproduce; can you provide more specific instructions?

**Comment by pihart** [comment] 2020-10-10 00:01
Are you testing on the latest version? I have it hosted here: https://pihart.github.io/qboard/

**Comment by pihart** [comment] 2020-10-10 00:01
(Make sure to drag away one of the pasted objects because they both get added in the same location)

**Comment by cjquines** [comment] 2020-10-10 00:04
couldn't repro there either. is your ctrl+v shortcut linked to paste? because if so then this is intended behavior

**Comment by pihart** [comment] 2020-10-10 00:05
It is. Why is this intended?

**Comment by cjquines** [comment] 2020-10-10 00:07
the clipboard api sucks. when we call the paste action we have no way of knowing if the system paste action is also happening at the same time without a heavy refactor? the default keybindings have been changed so that ctrl+v is no longer bound to paste so idk

**Comment by pihart** [comment] 2020-10-10 06:34
Can this not be tested here: https://github.com/cjquines/qboard/commit/5932e27b376347726861a7be2c73b5a59642319f#diff-b3afd2997c4961162817af5a45adc69cR167 ?

**Comment by cjquines** [comment] 2020-10-29 14:16
still exists actually; closing

**Closed by cjquines** 2020-10-29 14:16 UTC
Labels: wontfix
